#!/usr/bin/env bash
# SessionStart Hook: Multi-agent worktree isolation
#
# When in the main clone, prompts Claude to create a worktree first.
# When in a worktree, writes a session marker for isolation enforcement.

set -uo pipefail

# Skip if not a git repo
git rev-parse --git-dir &>/dev/null || exit 0

MAIN_WORKTREE=$(git worktree list --porcelain | head -1 | sed 's/^worktree //')
CURRENT_WORKTREE=$(git rev-parse --show-toplevel 2>/dev/null)

if [[ "$CURRENT_WORKTREE" == "$MAIN_WORKTREE" ]]; then
    WORKTREE_COUNT=$(git worktree list | wc -l | tr -d ' ')
    cat << EOF

<multi-agent-mode status="main-clone" action="create-worktree">
You are in the MAIN CLONE. If running parallel sessions, create a
worktree first to avoid conflicts:

  claude --worktree <task-name>

Or use the Agent tool with isolation: "worktree" for subagents.

Active worktrees: $WORKTREE_COUNT
If this is the only session, you can work directly on main.
</multi-agent-mode>

EOF
else
    # In a worktree — write session marker for isolation enforcement
    BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
    TASK=$(echo "$BRANCH" | sed 's|^claude/||')
    SESSION_FILE="$CURRENT_WORKTREE/.claude/worktree-session"

    mkdir -p "$CURRENT_WORKTREE/.claude"
    cat > "$SESSION_FILE" << MARKER
# Worktree Session Marker (auto-generated by session-start hook)
WORKTREE_PATH=$CURRENT_WORKTREE
MAIN_WORKTREE=$MAIN_WORKTREE
TASK_NAME=$TASK
BRANCH=$BRANCH
CREATED=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
MARKER

    cat << EOF

<multi-agent-mode status="isolated" worktree="$CURRENT_WORKTREE" branch="$BRANCH">
Worktree isolation active. Session marker written.
</multi-agent-mode>

EOF
fi

exit 0
